"""
Tutorial 01: Wannierization of GaAs valence bands using ASE
============================================================

This tutorial demonstrates how to use the ASE Wannier module to read
Wannier90 input files and perform Wannierization -- the construction of
maximally-localized Wannier functions (MLWFs).

System: Gallium Arsenide (GaAs) in the zinc-blende structure.
Goal:   Construct 4 MLWFs from the 4 valence bands, starting from
        sp3 projections on the As atom.

Required files (generated by a prior DFT + Wannier90 pw2wannier90 step):
  - gaas.win   -- Wannier90 input file (cell, atoms, k-grid, projections)
  - gaas.mmn   -- Overlap matrices <u_{n,k}|u_{m,k+b}> between Bloch states
  - gaas.amn   -- Projection coefficients <psi_{n,k}|g_m> for initial guesses
"""

import numpy as np
from pathlib import Path

from ase.dft.wannier import Wannier

# ---------------------------------------------------------------------------
# 0. Setup
# ---------------------------------------------------------------------------

# The 'seed' is the path prefix -- ASE will look for seed.win, seed.mmn, etc.
tutorial_dir = Path(__file__).resolve().parent
seed = tutorial_dir / 'gaas'

print("=" * 65)
print("  Tutorial 01: Wannierization of GaAs valence bands with ASE")
print("=" * 65)
print()

# Verify that the required input files exist
for ext in ['.win', '.mmn', '.amn']:
    fpath = seed.with_suffix(ext)
    assert fpath.exists(), f"Missing required file: {fpath}"
    print(f"  Found: {fpath.name}")
print()

# ---------------------------------------------------------------------------
# 1. Read Wannier90 input files and create the Wannier object
# ---------------------------------------------------------------------------
# The from_wannier90() class method reads .win, .mmn, and .amn files.
# It sets up the k-point grid, overlap matrices, and initial rotation
# matrices from the Wannier90 projection coefficients (.amn).
#
# Note: .nnkp and .eig files are optional. When absent, neighbor info
# is extracted from .mmn headers and eigenvalues are set to NaN
# (only needed for Hamiltonian interpolation, not for localization).

print("Reading Wannier90 files and creating Wannier object...")
print()

wan = Wannier.from_wannier90(
    seed=str(seed),
    initialwannier='amn',   # Use .amn projections as initial guess
    functional='std',        # Standard spread functional
    log=print,               # Print progress to stdout
)

print()
print(f"  Number of Wannier functions: {wan.nwannier}")
print(f"  Number of bands:             {wan.nbands}")
print(f"  Number of k-points:          {wan.Nk}")
print(f"  Number of b-vector dirs:     {wan.Ndir}")
print()

# ---------------------------------------------------------------------------
# 2. Inspect the crystal structure
# ---------------------------------------------------------------------------
# The .win file contains the unit cell and atomic positions.
# ASE parses these into an Atoms object.

atoms = wan.atoms
print("Crystal structure (from gaas.win):")
print(f"  Chemical formula: {atoms.get_chemical_formula()}")
print(f"  Cell (Angstrom):")
for i, v in enumerate(atoms.cell):
    print(f"    a{i+1} = [{v[0]:8.4f}, {v[1]:8.4f}, {v[2]:8.4f}]")
print(f"  Atomic positions (fractional):")
scaled = atoms.get_scaled_positions()
for sym, pos in zip(atoms.get_chemical_symbols(), scaled):
    print(f"    {sym:2s}  ({pos[0]:.4f}, {pos[1]:.4f}, {pos[2]:.4f})")
print()

# ---------------------------------------------------------------------------
# 3. Evaluate the initial (pre-localization) Wannier functions
# ---------------------------------------------------------------------------
# Before optimization, the Wannier functions are initialized from the .amn
# projections. Let's see how good the initial guess is.
#
# Key quantities:
#   - get_centers():          Wannier function centers in Cartesian coords
#   - get_spreads():          Spread (variance) of each WF in Angstrom^2
#   - get_functional_value(): The localization functional Tr[sum_d w_d |Z_d|^2]
#     This is MAXIMIZED during localization (higher = more localized).

centers_init = wan.get_centers()
spreads_init = wan.get_spreads()
functional_init = wan.get_functional_value()

print("Before localization (initial .amn projections):")
print("-" * 60)
print(f"  {'WF':>3s}  {'Center (Angstrom)':^36s}  {'Spread (A^2)':>11s}")
print(f"  {'':>3s}  {'x':>10s}  {'y':>10s}  {'z':>10s}  {'':>11s}")
print("-" * 60)
for w in range(wan.nwannier):
    cx, cy, cz = centers_init[w]
    s = spreads_init[w]
    print(f"  {w+1:3d}  {cx:10.5f}  {cy:10.5f}  {cz:10.5f}  {s:11.6f}")
print("-" * 60)
print(f"  Sum of spreads:         {np.sum(spreads_init):.6f} A^2")
print(f"  Localization functional: {functional_init:.6f}")
print()

# ---------------------------------------------------------------------------
# 4. Wannier localization (minimization of the spread functional)
# ---------------------------------------------------------------------------
# This is the key step: iteratively rotate the Bloch states to maximize
# the localization functional (equivalently, minimize the total spread),
# yielding maximally-localized Wannier functions.
#
# The localize() method uses steepest-descent optimization (MDmin).
# The optimizer maximizes Tr[w_d |Z_d|^2]; the spread decreases as
# the overlap matrix diagonal elements |Z_nn| approach unity.

print("Running localization...")
print("-" * 60)
wan.localize(step=0.25, tolerance=1e-8)
print("-" * 60)
print()

# ---------------------------------------------------------------------------
# 5. Evaluate the final (post-localization) Wannier functions
# ---------------------------------------------------------------------------

centers_final = wan.get_centers()
spreads_final = wan.get_spreads()
functional_final = wan.get_functional_value()

print("After localization:")
print("-" * 60)
print(f"  {'WF':>3s}  {'Center (Angstrom)':^36s}  {'Spread (A^2)':>11s}")
print(f"  {'':>3s}  {'x':>10s}  {'y':>10s}  {'z':>10s}  {'':>11s}")
print("-" * 60)
for w in range(wan.nwannier):
    cx, cy, cz = centers_final[w]
    s = spreads_final[w]
    print(f"  {w+1:3d}  {cx:10.5f}  {cy:10.5f}  {cz:10.5f}  {s:11.6f}")
print("-" * 60)
print(f"  Sum of spreads:         {np.sum(spreads_final):.6f} A^2")
print(f"  Localization functional: {functional_final:.6f}")
print()

# ---------------------------------------------------------------------------
# 6. Analysis: compare initial vs final spreads
# ---------------------------------------------------------------------------

print("Comparison: initial vs final")
print("-" * 50)
for w in range(wan.nwannier):
    delta = spreads_final[w] - spreads_init[w]
    print(f"  WF {w+1}: {spreads_init[w]:.6f} -> {spreads_final[w]:.6f}"
          f"  (delta = {delta:+.6f})")
print("-" * 50)
spread_reduction = np.sum(spreads_init) - np.sum(spreads_final)
print(f"  Total spread reduction:  {spread_reduction:+.6f} A^2")
functional_gain = functional_final - functional_init
print(f"  Functional gain:         {functional_gain:+.6f}")
print()

# ---------------------------------------------------------------------------
# 7. Physical interpretation
# ---------------------------------------------------------------------------
# For GaAs with sp3 projections on As, we expect the 4 MLWFs to be
# centered along the Ga-As bonds, shifted towards the As atom (since
# As is more electronegative). In the zinc-blende structure, these
# correspond to the 4 bonding sp3 orbitals.

# Average WF center
com = np.mean(centers_final, axis=0)
as_pos = atoms[[a.symbol == 'As' for a in atoms]].positions[0]

print("Physical interpretation:")
print(f"  Average WF center: ({com[0]:.4f}, {com[1]:.4f}, {com[2]:.4f}) A")
print(f"  As position:       ({as_pos[0]:.4f}, {as_pos[1]:.4f},"
      f" {as_pos[2]:.4f}) A")

# All spreads should be roughly equal (by symmetry of the 4 sp3 orbitals)
spread_std = np.std(spreads_final)
print(f"  Spread std. dev.:  {spread_std:.6f} A^2"
      f"  (should be ~0 by tetrahedral symmetry)")

# Distance from each WF center to the As atom
print(f"  Distance from As to each WF center:")
for w in range(wan.nwannier):
    d = np.linalg.norm(centers_final[w] - as_pos)
    print(f"    WF {w+1}: {d:.4f} A")
print()

# ---------------------------------------------------------------------------
# 8. Plot: convergence and WF centers (optional)
# ---------------------------------------------------------------------------

try:
    import matplotlib
    matplotlib.use('Agg')  # Non-interactive backend for saving to file
    import matplotlib.pyplot as plt

    print("Generating plots...")

    # --- Convergence plot ---
    # Re-create the Wannier object to record the convergence history
    wan2 = Wannier.from_wannier90(
        seed=str(seed),
        initialwannier='amn',
        functional='std',
    )

    # Capture per-iteration values from the optimizer log
    history = [wan2.get_functional_value()]

    class HistoryLogger:
        """Captures functional values printed during localization."""
        def __init__(self):
            self.values = []
        def __call__(self, *args):
            msg = ' '.join(str(a) for a in args)
            if msg.startswith('MDmin: iter='):
                for part in msg.split(','):
                    part = part.strip()
                    if part.startswith('value='):
                        self.values.append(float(part.split('=')[1]))

    logger = HistoryLogger()
    wan2.log = logger
    wan2.localize(step=0.25, tolerance=1e-10)
    history.extend(logger.values)

    fig, ax = plt.subplots(figsize=(7, 4.5))
    ax.plot(range(len(history)), history, 'o-', markersize=4, linewidth=1.2,
            color='steelblue')
    ax.set_xlabel('Optimization step')
    ax.set_ylabel('Localization functional (a.u.)')
    ax.set_title('Tutorial 01: GaAs MLWF localization convergence')
    ax.axhline(y=history[-1], color='gray', linestyle='--', alpha=0.5,
               label=f'Converged: {history[-1]:.6f}')
    ax.legend()
    ax.grid(True, alpha=0.3)
    fig.tight_layout()

    plot_path = tutorial_dir / 'tutorial01_convergence.png'
    fig.savefig(plot_path, dpi=150)
    print(f"  Saved: {plot_path.name}")

    # --- 3D plot of WF centers and atomic positions ---
    fig2 = plt.figure(figsize=(7, 6))
    ax2 = fig2.add_subplot(111, projection='3d')

    # Plot atoms
    for a in atoms:
        color = 'purple' if a.symbol == 'Ga' else 'green'
        ax2.scatter(*a.position, s=200, c=color, edgecolors='k', zorder=5)

    # Plot Wannier centers
    for w in range(wan.nwannier):
        ax2.scatter(*centers_final[w], s=80, c='red', marker='D',
                    edgecolors='k', zorder=4)

    # Draw lines from each WF center to both atoms (bond skeleton)
    for w in range(wan.nwannier):
        for a in atoms:
            ax2.plot([centers_final[w][0], a.position[0]],
                     [centers_final[w][1], a.position[1]],
                     [centers_final[w][2], a.position[2]],
                     'k--', alpha=0.3, linewidth=0.8)

    ax2.set_xlabel('x (A)')
    ax2.set_ylabel('y (A)')
    ax2.set_zlabel('z (A)')
    ax2.set_title('GaAs: Wannier function centers (red)\n'
                   'and atomic positions (Ga=purple, As=green)')

    from matplotlib.lines import Line2D
    legend_elements = [
        Line2D([0], [0], marker='o', color='w', markerfacecolor='purple',
               markersize=10, label='Ga'),
        Line2D([0], [0], marker='o', color='w', markerfacecolor='green',
               markersize=10, label='As'),
        Line2D([0], [0], marker='D', color='w', markerfacecolor='red',
               markersize=8, label='WF center'),
    ]
    ax2.legend(handles=legend_elements)

    plot2_path = tutorial_dir / 'tutorial01_centers.png'
    fig2.savefig(plot2_path, dpi=150)
    print(f"  Saved: {plot2_path.name}")
    print()

except ImportError:
    print("  (matplotlib not available -- skipping plots)")
    print()

# ---------------------------------------------------------------------------
# 9. Save the optimized state
# ---------------------------------------------------------------------------

save_path = tutorial_dir / 'gaas_wannier_state.json'
wan.save(str(save_path))
print(f"Saved optimized Wannier state to: {save_path.name}")
print("  (Can be loaded later with: Wannier.from_wannier90(seed, file=...))")
print()

print("=" * 65)
print("  Tutorial 01 complete!")
print("=" * 65)
